(define (problem p1)
	(:domain wolf-sheep)
	(:objects west east boat farmer sheep cabbage wolf)
	(:init
		(on farmer west)
		(on sheep west)
		(on cabbage west)
		(on wolf west)
		(farmer farmer)
		(boat boat)
		(shore west)
		(shore east)
		(sheep sheep)
		(cabbage cabbage)
		(wolf wolf)
	)
	(:goal
		(and
			(on farmer east)
			(on sheep east)
			(on cabbage east)
			(on wolf east)
		)
	)
)